_target_: beso.workspaces.kitchen_workspace_manager.FrankaKitchenManager
_recursive_: false

dataset_fn:
  _target_: beso.envs.franka_kitchen.dataloader.get_relay_kitchen_train_val
  data_directory: ${data_path}
  train_fraction:  ${workspaces.train_fraction}
  random_seed: ${seed}
  device: ${device}
  # scale_data: ${scale_data}
  window_size: ${window_size}
  goal_conditional: ${goal_conditional}
  future_seq_len: ${future_seq_length}
  only_sample_tail: False
  only_sample_seq_end: False
  obs_modalities: ${obs_modalities}

env_name: 'kitchen-all-v0'
seed: ${seed}
train_batch_size: 24
test_batch_size:  24
num_workers: 4
eval_n_times: 25
eval_n_steps: 280
device: ${device}
scale_data: ${scale_data}
train_fraction: 0.95
render: ${render}
obs_modalities: ${obs_modalities}
goal_seq_len: ${future_seq_length}

